# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 551)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.sa_messages = QtWidgets.QWidget()
        self.sa_messages.setGeometry(QtCore.QRect(0, 0, 360, 481))
        self.sa_messages.setObjectName("sa_messages")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sa_messages)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vl_message_list = QtWidgets.QVBoxLayout()
        self.vl_message_list.setObjectName("vl_message_list")
        self.gridLayout_2.addLayout(self.vl_message_list, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.sa_messages)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 2)
        self.te_message = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_message.setObjectName("te_message")
        self.gridLayout.addWidget(self.te_message, 1, 1, 1, 1)
        self.btn_send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.gridLayout.addWidget(self.btn_send, 1, 2, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 280, 510))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.widget)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_send.setText(_translate("MainWindow", "Send"))
